const LETTERSURI = [
  { letter: "ي", file: "29" },
  { letter: "ء", file: "28" },
  { letter: "هـ", file: "27" },
  { letter: "و", file: "26" },
  { letter: "ن", file: "25" },
  { letter: "م", file: "24" },
  { letter: "ل", file: "23" },
  { letter: "ك", file: "22" },
  { letter: "ق", file: "21" },
  { letter: "ف", file: "20" },
  { letter: "غ", file: "19" },
  { letter: "ع", file: "18" },
  { letter: "ظ", file: "17" },
  { letter: "ط", file: "16" },
  { letter: "ض", file: "15" },
  { letter: "ص", file: "14" },
  { letter: "ش", file: "13" },
  { letter: "س", file: "12" },
  { letter: "ز", file: "11" },
  { letter: "ر", file: "10" },
  { letter: "ذ", file: "9" },
  { letter: "د", file: "8" },
  { letter: "خ", file: "7" },
  { letter: "ح", file: "6" },
  { letter: "ج", file: "5" },
  { letter: "ث", file: "4" },
  { letter: "ت", file: "3" },
  { letter: "ب", file: "2" },
  { letter: "أ", file: "1" }
];

export default LETTERSURI;
